ERROR 2020-07-16 08:14:45,441 django.request.log_response:228- Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:14:45,442 django.server.log_message:157- "GET / HTTP/1.1" 500 99367
ERROR 2020-07-16 08:14:45,679 django.request.log_response:228- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:14:45,680 django.server.log_message:157- "GET /favicon.ico HTTP/1.1" 500 99309
ERROR 2020-07-16 08:16:03,240 django.request.log_response:228- Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:16:03,241 django.server.log_message:157- "GET / HTTP/1.1" 500 99367
ERROR 2020-07-16 08:19:38,901 django.request.log_response:228- Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:19:38,903 django.server.log_message:157- "GET / HTTP/1.1" 500 99367
ERROR 2020-07-16 08:21:19,190 django.request.log_response:228- Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:21:19,193 django.server.log_message:157- "GET / HTTP/1.1" 500 99181
ERROR 2020-07-16 08:21:19,675 django.request.log_response:228- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Dev/coach/backend/config/views.py", line 16, in index
    return render(request, "frontend/index.html")
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/Dev/coach/env/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/index.html
ERROR 2020-07-16 08:21:19,678 django.server.log_message:157- "GET /favicon.ico HTTP/1.1" 500 99123
